### ISSUE TITLE
Enchants aren't stripped from books

### ISSUE THREAD

**Issue by x86-39** [jeremynoesen/CourierNew#15]
In servers with a creative world this can allow players to bring hacked books with impossible enchants into the server.
By getting a written book with enchants (for example, looting 255) in a creative world, you can /post this to yourself (or others) and quickly go to the survival world to get it. 

This can be remedied by denying /post permissions in creative worlds/gamemodes if the permission plugin has this functionality, but I'm of the opinion that the plugin could deal with this too.

I think the ideal solution here is to have a permission that strips the enchants of the book if it isn't set. This can be done with https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#hasEnchants() and https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#removeEnchant(org.bukkit.enchantments.Enchantment)

**Comment by maeeeeee** [comment]
not sure if stripping enchants is ever necessary, checking the value of hasEnchants in the letter checker seems like it would get the job done

**Comment by jeremynoesen** [comment]
This issue is covered in more detail in #19. Closing this, as it is basically a duplicate.
