### ISSUE TITLE
Some usernames are not able to be used when sending letters

### ISSUE THREAD

**Issue by EnvyingGolem47** [jeremynoesen/CourierNew#2]
Hi, I am using a spigot 1.14.2 server and some of the players can receive but some can't because the command says "They do not exist" even though they very well do. I tried looking it up on other places to try and find a quick similar fix but I have been unable to find similar problems. I was wondering if there was a way to send letters to these players using either their UUID or if there was another easy fix I could tell others to do when sending letters to the unable to receive players.
Thank you!

(If you need any more issues please feel free to let me know)

**Comment by jeremynoesen** [comment]
Hey! I'm so sorry for such a late reply! This will be fixed in the next version, which will be released soon. It is actually fixed in the current dev build, but I don't recommend compiling that as it will cause weird glitches. I will try to get it out in a few days.

**Comment by jeremynoesen** [comment]
I was able to filter out the beta features and push out a new release to fix this issue just now. Download 1.2.7 to fix this issue
