### ISSUE TITLE
Could you add an option to change the mob who delivers the mail?

### ISSUE THREAD

**Issue by halberfan** [jeremynoesen/CourierNew#3]
Hey, my server got a problem. We disabled Villagers so they aren't able to spawn. Would it be possible to change the mob type? I'd love it

Greetings

**Comment by jeremynoesen** [comment]
I was actually working on allowing customization of the postman entity, but I have yet to finish it. I will keep you up to date with any changes to this behavior in the future.

**Comment by jeremynoesen** [comment]
This feature was added in the latest update, forgot to let you know!
