### ISSUE TITLE
1.8 Support

### ISSUE THREAD

**Issue by Ismael-GT** [jeremynoesen/CourierNew#4]
Is possible add 1.8 support?, thank you!

**Comment by jeremynoesen** [comment]
I could try, but due to the great amount of API changes 1.13 brought about, there is a chance it may not be possible. I will get back to you after I try this.

**Comment by Ismael-GT** [comment]
Thanks to answer Jeremy :),  there is plugins have done it with multi-version support. It will be great, all my players will tell you thank you, this plugin is very, very good.

**Comment by jeremynoesen** [comment]
Due to changes in recent versions of Minecraft, I'm sorry to say that I will not be adding legacy version support to the plugin.
