### ISSUE TITLE
Immortal Postmen/Infinite Mob Creation

### ISSUE THREAD

**Issue by NikoEatsPancakes** [jeremynoesen/CourierNew#5]
**Describe the bug**
Postmen can be infinitely spawned and will not despawn.

**Steps to reproduce**
1. Send a letter to yourself or receive a letter from someone else
2. Do /unread to summon the postman
3. Relog
4. The postman will now be invincible and will never despawn.

**Comment by jeremynoesen** [comment]
I will look into this soon. For now, you can use a Minecraft kill command to kill the postmen. Sorry for the inconvenience for now.

**Comment by jeremynoesen** [comment]
Could not replicate the issue, even on the same server. I plan to clean up the way the postman works eventually.
